services:
  php:
    build: .
    working_dir: /app
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./app/:/app
      - caddy_data:/data
      - caddy_config:/config
    tty: true

volumes:
  caddy_data:
  caddy_config: